apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: dev
  labels:
    app: postgres
spec:
  # Headless Service (clusterIP: None)
  # ใช้สำหรับให้ StatefulSet Pod มี Stable network identity
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres