apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dev
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  sessionAffinity: ClientIP