apiVersion: v1
kind: Pod
metadata:
  name: backup-access
  namespace: dev
  labels:
    app: backup-access
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', '3600']
    volumeMounts:
    - name: backup-storage
      mountPath: /backup
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  volumes:
  - name: backup-storage
    persistentVolumeClaim:
      claimName: backup-pvc